
Problem 6-1
-----------
Write a higher order function that takes an Integer and divides it by 10 using point free
style.

Problem 6-2
-----------
Write a function that takes a function with type `Double -> Double` and a list of
+Doubles+ and maps the function over the list. Test your result with a few functions
like `f x = 2 x` and `g x = x * x`. Try passing the functions in as lambdas.

Problem 6-3
-----------
Write a function that takes a list of numbers and a binary comparison function and uses 
recursion to apply the function across list. Test your function with `max` and `min` and 
make sure it behaves correctly.

Problem 6-4
-----------
Re-implement the function from problem 6-3 with a right-fold.

Problem 6-5
-----------
Write a program that computes the elements of Pascal's triangle using recursion. The 
function should take an Integral argument and produce the row of Pascal's Triangle 
corresponding to that row. So, the output should look like:

  Prelude> :l problem0605.hs 
  [1 of 1] Compiling Main             ( problem0605.hs, interpreted )
  Ok, modules loaded: Main.
  *Main> pascal 1
  [1]
  *Main> pascal 2
  [1,1]
  *Main> pascal 3
  [1,2,1]
  *Main> pascal 4
  [1,3,3,1]
  *Main> pascal 5
  [1,4,6,4,1]

Problem 6-6
-----------
Using recursion, implement Dijkstra's algorithm to find the greatest common denominator
of two Integral numbers. (The algorithm is that if the two arguments are equal, they are
the GCD, but if the first is larger than the second, recursively call the function again 
the first minus the second and the second, while if the seond is larger, call the function
again using the first and the second minus the first.)


Problem 6-7
-----------
Compute the integer powers of a number recursively (so 2 to the 3rd power, or 4 to the -1st
power, etc.). Use the `Fractional` type for the base and the Integral type for the numerator.
Results should look like:

  *Main> powers 2 3
  8.0
  *Main> powers 2 (-3)
  0.125
  *Main> powers 2 0
  1.0


