
Problem 4-1
------------
Recall this problem from Chapter 2: Write a function that takes a String for an argument and 
returns ``is Rad!'' if the argument is ``Earth'' and ``is Cool!'' if the argument is ``Mars'' 
and ``is Ok.'' otherwise. Re-write this function using guards. Make sure you write a type
signature (always write a type signature for all the exercises).

Problem 4-2
-----------
Rewrite the function from problem 4-1 using a `case` expression.

Problem 4-3
-----------
Write a function that takes an integer argument between 1 and 9 (inclusive) and returns
the result as a String. So, `f 1` would return ``One''. Write the function using guards
and then again using a `case` expression.

Problem 4-4
-----------
Write a function that takes a string and replaces all ``,'' characters with ``:'', all
``:'' with ``;'', and all ``;'' with ``,''. So, ``the;quick:brown,fox'' should become
``the,quick;brown:fox''.

Problem 4-5
-----------
Use `let` and `where` expressions, along with list comprehensions, to write a 
function that takes a list of numbers and transforms it into two different lists,
and zips them together. The first list should be one where each element becomes a product 
of itself and itself minus one, and the other should be one where each element becomes
a product of itself and one minus itself. 

Problem 4-6
-----------
Write the ``Hello World'' of functional programming - a function that returns the nth
Fibbonacci number. Look carefully at the definiiton of the `factorial` function 
in this chapter. The Fibbonacci sequence begins with 1, 1 and each successive element is 
the sum of the previous two. So the sequence goes 1, 1, 2, 3, 5, 8, 13, etc. (If you 
are concerned about efficiency, don't be yet.)

Problem 4-7
-----------
The trignometric sine and cosine functions (like all continuously differentiable functions)
may be represented as an inifite polynomial called the Taylor expansion. For example,
`sin x = x - x**3 / 3! + x**5 / 5! - ...` and
`cos x = 1 - x**2 / 2! + x**4 / 4! - ...`.
Using list comprehensions and `let` and `where` statements, implement sine and cosine 
functions that compute those values to an order the user provides.

