
Problem 7-1
-----------
Compose a script in wich you import Data.List, Data.Map.Strict, Data.Set, and
Data.Foldable.

Problem 7-2
-----------
Compose a script like you wrote for problem 7-1, but do qualified imports.

Problem 7-3
-----------
Compose another script where you import the same libraries as in problems 7-1 
and 7-2, but this time import only one function from each module. Look at 
http://hackage.haskell.org/ for some example functions.

Problem 7-4
-----------
Compose yet another script importing the same modules as in the previous problems, 
but this time hide a function for each module. Does it make sense to ``combine'' this 
problem with the previous problem (i.e., import a specific set of functions but also
hide some functions)?
 
Problem 7-5
-----------
Create a module called ``Progressions.hs'' and export two functions, `arithmetic` and
`geometric`. These functions represent the sums of the arithmetic and geometric series
respectively. You don't need to fill in the functions for this exercise, just set
them to be undefined like so: `arithmetic = undefined`. Write a script that imports 
this module (if you defined the functions, test them).

Problem 7-6
-----------
Create a directory and name it ``Numberary.'' Copy your ``Progressions.hs'' code from
problem 7-5 into that directory. Edit the code so that it is part of the 
`Numberary.Progressions` module. Write a script that imports this module (if you defined
the functions, test them).

Problem 7-7
-----------
Add a directory to ``Numberary'' called ``Combinatorics'' and add the binomial 
and multinomial functions you wrote for Chapter 2 into that subdirectory. Make that
code a module called ``Multinomials'' (so, the total will be
`Numberary.Combinatorics.Multinomials`). Be sure you only export the `binomial` and 
`multinomial` functions and not any helper functions. Write a script that imports this 
module and tests the functions. Make sure that if you try to call any helper functions
that the script will not load into GHCi.

Problem 7-8
-----------
Recall that in Chapter 4 we created sine and cosine implementations that took
a floating point number and an integral order for a Taylor expansion and provided
trigonometric values for those functions. Create a module that exports `sine`, `cosine`,
and `tangent` functions that return Doubles and instead of asking for an order,
computes the functions to some accuracy specified inside the module. Add these 
functions to your ``Numberary'' module under ``Trigonometric.hs''.

Problem 7-9
-----------
In Data.Char there is a function, `digitToInt` that takes a +Char+ and changes 
it to a +Int+, provide the character is a valid base 16 number (so, +0+ through
+f+, and it accepts upper-case characters). In the base environment there is a 
function, `show` that changes a number into a string representation of that 
number (it does other things too, try `:t show` in GHCi). Use these two functions
to write a function that calculates the first number that is equal to the sum of
the fifth power of its digits. For example, `93084 = 9^5 + 3^5 + 0^5 + 8^5 + 4^5`
is equal to the sum of the fifth power of its digits, but it is not the _first_ 
such number. (This question is inspired by Project Euler (http://projecteuler.net) 
problem number 30.)
